name: Run Get Greeting

on: [repository_dispatch]

jobs:
  demo-get-greeting:
    if: github.event.action == 'get_greeting'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Deploy Demo Workflow "Get Greeting"
        uses: jwulf/zeebe-action@master
        with:
          clientConfig: ${{ secrets.ZEEBE_CLIENT_CONFIG }}
          operation: deployWorkflow
          bpmnFilename: bpmn/demo-get-greeting.bpmn
      - name: Execute Demo Workflow "Get Greeting"
        uses: jwulf/zeebe-action@master
        with:
          operation: createWorkflowInstanceWithResult
          bpmnProcessId: demo-get-greeting
          variables: '{"greeting":{"morning":"Good morning!","afternoon":"Good afternoon!","night":"Good night!"}}'
          requestTimeoutSeconds: 15
