name: Deploy Workflows

on: [repository_dispatch]

jobs:
  deploy-workflows:
    if: github.event.action == 'deploy_workflows'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Deploy Demo Workflows
        uses: jwulf/zeebe-action@master
        with:
          clientConfig: ${{ secrets.ZEEBE_CLIENT_CONFIG }}
          operation: deployWorkflow
          bpmnDirectory: bpmn
