name: Start Workers

on: [repository_dispatch]

jobs:
  start-workers:
    if: github.event.action == 'start_workers'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Start Workers
        uses: jwulf/zeebe-action@master
        with:
          clientConfig: ${{ secrets.ZEEBE_CLIENT_CONFIG }}
          operation: startWorkers
          workerHandlerFile: workers/workers.js
          workerLifetimeMins: 2
